	[
	GlobalContext=DOMWindow&WorkerGlobalScope,
    ActiveDOMObject,
    Constructor,
    ConstructorCallWith=ScriptExecutionContext,
    JSNoStaticTables,
	] interface AnonXMLHttpRequest : XMLHttpRequest {
	};
